name: xrayapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+15

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  
  lottie: ^3.0.0 # Use the latest version
  
  # Packages
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8

  http: ^1.6.0
  image_picker: ^1.2.1
  intl: 0.20.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  device_info_plus: ^12.3.0
  android_id: ^0.5.1
  purchases_flutter: ^9.12.0
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1

# FLUTTER CONFIGURATION SECTION
flutter:
  uses-material-design: true
  assets:
    - assets/scanner_animation.json
    - assets/translations/
    - assets/logo.png
    - assets/applogo.png
    - assets/scanner2.json
    - assets/fjyn.png

# Add this at the very bottom of your pubspec.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/applogo.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/applogo.png"
  fadaptive_icon_foreground_inset: 100

  min_sdk_android: 21 # Required for modern Android compatibility